### PR TITLE
update using a26 data

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
>Also can you restore the file in ao ?:)

@StanleySweet Are you sure? I could, but it doesn't appear in the a26 data:

```
[andy@prometheus art]((HEAD detached at A26))$ find . -name textures.xml
./textures/ui/global/button/textures.xml
./textures/ui/loading/progressbar/textures.xml
./textures/ui/pregame/backgrounds/textures.xml
./textures/ui/session/textures.xml
./textures/ui/session/icons/textures.xml
./textures/ui/session/icons/status_effects/textures.xml
./textures/ui/reference/portraits/textures.xml
./textures/misc/textures.xml
./textures/terrain/types/textures.xml
./textures/textures.xml
./textures/skins/gaia/textures.xml
./textures/animated/water/textures.xml
[andy@prometheus art]((HEAD detached at A26))$ pwd
/home/andy/src/0ad/binaries/data/mods/public/art
[andy@prometheus art]((HEAD detached at A26))$ cd ..
[andy@prometheus public]((HEAD detached at A26))$ cd ../mod/art/textures/
[andy@prometheus textures]((HEAD detached at A26))$ find . -name textures.xml
./ui/textures.xml
./textures.xml
```

**Comment by StanleySweet** [comment]
Yeah I'm sure it's mine :)

**Comment by andy5995** [comment]
> Yeah I'm sure it's mine :)

ok! So it should be there even though it's not in a26 data? (I just want to make absolutely sure we're clear)

**Comment by StanleySweet** [comment]
Yes. 
```
$ find -name 'textures.xml'
./mod/art/textures/textures.xml
./mod/art/textures/ui/textures.xml
./mod/fonts/textures.xml
./public/art/textures/animated/water/textures.xml
./public/art/textures/misc/textures.xml
./public/art/textures/skins/gaia/textures.xml
./public/art/textures/terrain/types/textures.xml
./public/art/textures/textures.xml
./public/art/textures/ui/global/button/textures.xml
./public/art/textures/ui/loading/progressbar/textures.xml
./public/art/textures/ui/pregame/backgrounds/textures.xml
./public/art/textures/ui/reference/portraits/textures.xml
./public/art/textures/ui/session/icons/status_effects/textures.xml
./public/art/textures/ui/session/icons/textures.xml
./public/art/textures/ui/session/textures.xml
```

Seems I was missing an extra one in the font folder that should be added.

**Comment by andy5995** [comment]
> Seems I was missing an extra one in the font folder that should be added.

>fonts/textures.xml

It already exists in this repo and there are no changes.

**Pull request merged**
